app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bases.urls')),
    path('pages/', include('paginas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('allauth.urls')),
    path('control/', include(('ctrl_comb.urls','control'),namespace="control")),
]

bases/urls.py
from django.urls import path

from .views import *

app_name="core"

urlpatterns = [
    # path('',primera_vista,name="primera_vista")
    path('',HomeView.as_view(),name="home")
]

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import *

app_name="usuarios"

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('login2/',
         auth_views.LoginView.as_view(template_name="usuarios/login2.html")
         ,name="login2"),
    path('registro/', RegistroUsuarioView.as_view(),name="registro"),
]

bases/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE,related_name="+")
    fc = models.DateTimeField(auto_now_add=True)
    um = models.ForeignKey(User, on_delete=models.SET_NULL,related_name="+",
                           blank=True,null=True)
    fm = models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

bases/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.contrib.auth.models import AnonymousUser
from django.urls import reverse_lazy

from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin, \
      PermissionRequiredMixin


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class MixinFormInvalid:
    def form_invalid(self,form):
        response = super().form_invalid(form)
        if is_ajax(request=self.request):
           return JsonResponse(form.errors,status=400)
        else:
            return response

class SinAutorizacion(LoginRequiredMixin,
                      PermissionRequiredMixin,
                      MixinFormInvalid) :
    login_url = "bases:login"
    raise_exception = False
    redirect_field_name = "redirect_to"
    
    def handle_no_permission(self):
        if not self.request.user == AnonymousUser():
            self.login_url = "pages:forbidden"
        return HttpResponseRedirect(reverse_lazy(self.login_url))

def primera_vista(request):
    return HttpResponse("Hola Mundo, desde el <b>Curso de Django para profesiones de Daniel Bojorge</b>")


class HomeView(TemplateView):
    template_name = "bases/home.html"


class MixinSaveUser:
    def form_valid(self,form):
        print(f"************{form.instance.id} --- {self.request.user.id} *******************")

        if form.instance.id:
            form.instance.um = self.request.user
        else:
            form.instance.uc = self.request.user
        
        return super().form_valid(form)

bases/templates/bases/delete.html
{% extends "base.html" %}

{% block contenido %}
<form action="" method="post">
    {% csrf_token %}
{% include "fragments/titulo.html" with titulo="Borrar"  %}

    {% include "fragments/card_start.html" with header="Borrar" %}
    ¿Eliminar {{obj}}?
    <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Si, Eliminar</button>
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success">
        <span class="fa fa-undo"></span>No, Cancelar
    </a>
    {% include "fragments/card_finish.html" %}
</form>
{% endblock %}

bases/templates/bases/home.html
{% extends "base.html" %}

{% block contenido %}

{% include "fragments/titulo.html" with titulo="Inicio"  %}

    {% include "fragments/card_start.html" with header="Bienvenido a la Aplicación" %}
      <h4 class="card-title">{% if user.is_authenticated %} Hola {{user.email}} {% else %}
        <a href="{% url 'usuarios:login' %}">Login</a>
        <a href="{% url 'usuarios:login2' %}">Login 2</a>
         {% endif%}
      </h4>
      <p class="card-text">{% lorem 5 %}</p>
      {% include "fragments/card_finish.html" %}
{% endblock %}