app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bases.urls')),
    path('pages/', include('paginas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('allauth.urls')),
    path('control/', include(('ctrl_comb.urls','control'),namespace="control")),
]

bases/urls.py
from django.urls import path

from .views import *

app_name="core"

urlpatterns = [
    # path('',primera_vista,name="primera_vista")
    path('',HomeView.as_view(),name="home")
]

ctrl_comb/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('mark/',MarkList.as_view(),name="mark_list"),
    path("mark/save",mark_save,name="mark_save"),
    path("mark/delete/<int:pk>",mark_delete,name="mark_delete"),
    path("mark/edit/<int:pk>",mark_edit,name="mark_edit"),

    path('models/',ModeloList.as_view(),name="modelo_list"),
    path("models/new",ModeloNew.as_view(),name="modelo_new"),
    path("models/<int:pk>",ModeloEdit.as_view(),name="modelo_edit"),
    path("models/delete/<int:pk>",ModeloDelete.as_view(),name="modelo_delete"),
    path("models/modal/<int:pk>",ModeloEditModal.as_view(),name="modelo_edit_modal"),
    path("models/modal/new",ModeloNewModal.as_view(),name="modelo_new_modal"),
    path("models/dt",modelo_dt,name="modelo_dt"),

    path("vehicles/",VehiculoList.as_view(),name="vehiculo_list"),
    path("vehicles/dt",vehiculo_dt,name="vehiculo_dt"),
    path("vehicles/new",VehiculoNewModal.as_view(),name="vehiculo_new"),
    path("vehicles/modal/<int:pk>",VehiculoEditModal.as_view(),name="vehiculo_edit"),
    path("vehicles/delete/<int:pk>",VehiculoDelete.as_view(),name="vehiculo_delete"),
]

paginas/urls.py
from django.urls import path
from .views import *

app_name="pages"
urlpatterns = [
    path('about',AboutView.as_view(),name="about"),
    path('forbidden',ForbiddenView.as_view(),name="forbidden"),
]

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import *

app_name="usuarios"

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('login2/',
         auth_views.LoginView.as_view(template_name="usuarios/login2.html")
         ,name="login2"),
    path('registro/', RegistroUsuarioView.as_view(),name="registro"),
]

templates/fragments/card_finish.html
</div>
</div>

templates/fragments/card_start.html
<div class="card border-danger mb-3" style="max-width: 90%">
    <div class="card-header">{{ header|default:"" }}</div>
    <div class="card-body">

templates/fragments/datatable.html
{% load static %}

<script>
    var tbl;
$(function(){
    tbl=$(tblName).DataTable({
        language:{
            url: "{% static 'plugins/datatable/es.json' %}"
        },
        ajax:{
            url: tblUrl,
            dataSrc: "datos"
        },
        columns: dtColumns,
        dom: 'Bfrtip',
        processing:true,serverSide:true,pageLength:15,
    })
})

    function borrar(id,d,url)
    {
        Swal.fire({
        title: '¿Procedo?',
        text: `Procedes a eliminar ${d}`,
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
        if (result.isConfirmed) {
            url = `${url}${id}`
            $.ajax({
                headers:{"X-CSRFToken":"{{ csrf_token }}"},
                type:"POST",
                url:url,
                success: function(r,textStatus,xhr){
                    if(xhr.status==200){
                        Swal.fire(
                            'Borrado',
                            `${d} Borrado Satisfactoriamente`,'success'
                            ).then(
                                function(){
                                    // location.reload()
                                    tbl.ajax.reload()
                                }
                            )
                    }
                },
                error: function(jqXHR,textStatus,error){
                    Swal.fire("Error",textStatus,"error")
                }
            })
        }
        })
    }


    $("#tbl").on("click","td.editor-delete",function(e){
        e.preventDefault()
        var rows = tbl.rows(this).data()
        // console.log(rows)
        var row = rows[0]
        // console.log(row.id)
        var id = row.id
        // var d = row.descript
        var d = ""
        descDelete.split(",").forEach(e => {
            if(row.hasOwnProperty(e)){
                if(d.length>0){
                    d += " - "
                }
                d += row[e]
            }
        })

        borrar(id,d,urlDelete)
    })

    $("#tbl").on("click","td.editor-edit",function(e){
        e.preventDefault()
        var rows = tbl.rows(this).data()
        // console.log(rows)
        var row = rows[0]
        // console.log(row.id)
        var id = row.id
        var url = `${dtUrlEdit}/${id}`
        // alert(url)
        abrir_modal(url)
    })
</script>

templates/fragments/menu.html
{% load socialaccount %}
{% providers_media_js %}


<div class="bs-docs-section clearfix">
    <div class="row">
        <div class="bs-component">
            <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">DJPro - DEBS</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarColor01">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <!-- <a class="nav-link active" href="{% url 'core:home' %}">Inicio
                                </a> -->
                                <div class="nav-link"
                                 hx-get="{% url 'core:home' %}" hx-push-url="true"
                                 hx-trigger="click"
                                 hx-target="#body"
                                 hx-swap="outerHTML"
                                 style="cursor: pointer;"
                                >Inicio</div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Registrar</a>
                            </li>
                            <!-- <li class="nav-item">
                                <a class="nav-link" href="#">Pricing</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li> -->
                            {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                                    aria-haspopup="true" aria-expanded="false">Catálogos</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#"
                                     hx-get="{% url 'control:mark_list' %}"
                                     hx-triger="click" hx-target="#body"
                                     hx-push-url="true"
                                     style="cursor: pointer;"
                                    >Marcas</a>
                                    {% if perms.ctrl_comb.view_modeo %}
                                    <a class="dropdown-item" href="{% url 'control:modelo_list' %}">Modelos</a>
                                    {% endif %}
                                    {% if perms.ctrl_comb.view_vehiculo %}
                                    <a class="dropdown-item" href="{% url 'control:vehiculo_list' %}">Vehículos</a>
                                    {% endif %}
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </div>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'pages:about' %}">Acerca de...</a>
                            </li>
                        </ul>
                        <div class="d-flex">
                            {% if user.is_authenticated %}
                            <!-- <a href="{% url 'usuarios:logout' %}">Salir</a> -->
                            <div class="text-info" hx-get="{% url 'usuarios:logout' %}"
                                hx-trigger="click" hx-target="#body" style="cursor: pointer;">Salir
                            </div>
                            {% else %}
                            <!-- <a href="{% url 'usuarios:login' %}">Login</a>
                            | <a href="{% url 'usuarios:registro' %}">Registro</a>
                            | <a href="{% provider_login_url 'google' %}?next=/">Google</a> -->
                            <div class="text-info" hx-get="{% url 'usuarios:login' %}" hx-push-url="true"
                                hx-trigger="click" hx-target="#body" style="cursor: pointer;">Login</div>&nbsp; &nbsp;
                            <div class="text-info" hx-get="{% url 'usuarios:registro' %}" hx-push-url="true"
                                hx-trigger="click" hx-target="#body" style="cursor: pointer;" hx-push-url="true">Registro</div>&nbsp; &nbsp;
                            <div class="text-info" hx-get="{% provider_login_url 'google'%}?next=/" hx-push-url="true"
                                hx-trigger="click" hx-target="#body" style="cursor: pointer;">Google</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

templates/fragments/titulo.html
<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h1 id="indicators">{{ titulo|default:"Título de la Página"}}</h1>
        </div>
    </div>
</div>