app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bases.urls')),
    path('pages/', include('paginas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('allauth.urls')),
    path('control/', include(('ctrl_comb.urls','control'),namespace="control")),
]

ctrl_comb/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('mark/',MarkList.as_view(),name="mark_list"),
    path("mark/save",mark_save,name="mark_save"),
    path("mark/delete/<int:pk>",mark_delete,name="mark_delete"),
    path("mark/edit/<int:pk>",mark_edit,name="mark_edit"),

    path('models/',ModeloList.as_view(),name="modelo_list"),
    path("models/new",ModeloNew.as_view(),name="modelo_new"),
    path("models/<int:pk>",ModeloEdit.as_view(),name="modelo_edit"),
    path("models/delete/<int:pk>",ModeloDelete.as_view(),name="modelo_delete"),
    path("models/modal/<int:pk>",ModeloEditModal.as_view(),name="modelo_edit_modal"),
    path("models/modal/new",ModeloNewModal.as_view(),name="modelo_new_modal"),
    path("models/dt",modelo_dt,name="modelo_dt"),

    path("vehicles/",VehiculoList.as_view(),name="vehiculo_list"),
    path("vehicles/dt",vehiculo_dt,name="vehiculo_dt"),
    path("vehicles/new",VehiculoNewModal.as_view(),name="vehiculo_new"),
    path("vehicles/modal/<int:pk>",VehiculoEditModal.as_view(),name="vehiculo_edit"),
    path("vehicles/delete/<int:pk>",VehiculoDelete.as_view(),name="vehiculo_delete"),
]

ctrl_comb/models.py
from django.db import models
from django.urls import reverse

from bases.models import ClaseModelo

class Mark(ClaseModelo):
    descript = models.CharField(
        max_length=50,
        unique=True
    )

    def __str__(self):
        return self.descript
    
    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"
        

class Modelo(ClaseModelo):
    descript = models.CharField(
        max_length=50,
        db_comment = "Descripción del Modelo de Vehículo",
    )
    mark = models.ForeignKey(Mark,
                             on_delete= models.PROTECT)
    def __str__(self):
        return f"{self.mark} - {self.descript}"
    
    class Meta:
        verbose_name_plural = "Modelos"
        db_table_comment = "Modelos de Vehículos"
        permissions = [
            ("permiso_especial","Puede Leer y Editar Modelos"),
        ]


class Vehiculo(ClaseModelo):
    modelo =  models.ForeignKey(Modelo, on_delete=models.RESTRICT)
    register= models.CharField(
        max_length=50,
        db_column="Matricula Vehículo",
        help_text="Matricula Vehículo"
    )
    year =models.PositiveSmallIntegerField(help_text="Año del Vehículo")

    TIPO_CHOICES = [
        ('MOT','Motocicleta'),
        ('CAP','Caponera'),
        ('SUV','Camioneta (SUV)'),
        ('PIK', 'PickUp'),
        ('SED', 'Sedán'),
        ('TAX', 'Taxi'),
        ('MIC', 'Microbús'),
        ('BUS', '(Auto)BUS'),
        ('CAM', 'Camión'),
    ]
    tipo = models.CharField(choices=TIPO_CHOICES, max_length=3,
                            default='SED')
    class UnidadMedida(models.IntegerChoices):
        GALONES = 1
        LITROS = 2

    unidad_medida = models.IntegerField(choices=UnidadMedida.choices,
                                        default= 1)
    @property
    def factor(self):
        f = 1
        if self.unidad_medida == 2:
            f = 0.264172
        return f

    def __str__(self):
        return self.register
    
    def get_absolute_url(self):
        return reverse("vehiculo_edit",kwargs={'pk':self.pk})
    
    class Meta:
        verbose_name_plural = "Vehículos"
        db_table_comment = "Vehículos"

ctrl_comb/forms.py
from django import forms

from .models import *

class MarkForm(forms.ModelForm):
    class Meta:
        model = Mark
        fields = "__all__"
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class ModeloForm(forms.ModelForm):
    class Meta:
        model=Modelo
        fields = ["mark","descript"]


class VehiculoForm(forms.ModelForm):
    class Meta:
        model=Vehiculo
        fields = ["modelo","register","year","tipo","unidad_medida"]

ctrl_comb/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import *
from django.urls import reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from .models import *
from .forms import *
from bases.views import SinAutorizacion,MixinSaveUser

# class MarkList(LoginRequiredMixin,ListView):
class MarkList(SinAutorizacion,ListView):
    template_name="ctrl_comb/mark.html"
    model=Mark
    context_object_name = "obj"
    ordering= ["descript"]
    login_url = "usuarios:login"
    permission_required = "ctrl_comb.view_mark"


def mark_save(request):
    context = {}
    template_name = "ctrl_comb/mark-list.html"

    if request.method == "POST":
        i = request.POST.get("id")
        d = request.POST.get("descript")
        print(f"******************* {request.user}.{request.user.id} - {i} *********")
        u = request.user
        o = None

        if i:
            o = Mark.objects.filter(id=i).first()
        else:
            o = Mark.objects.filter(descript=d).first()
        
        if o:
            o.descript = d
            o.um = u
            o.save()
        else:
            o = Mark.objects.create(descript = d,uc = u)

    obj = Mark.objects.all().order_by("descript")
    r = Mark.objects.filter(id = o.id).first()
    context["obj"] = obj
    context["reg"] = r

    return render(request,template_name,context)


def mark_delete(request,pk):
    context={}
    template_name = "ctrl_comb/mark-list.html"

    o = Mark.objects.filter(id=pk).first()
    o.delete()

    obj = Mark.objects.all().order_by("descript")
    context["obj"] = obj

    return render(request,template_name,context)


def mark_edit(request,pk=None):
    context={}
    template_name = "ctrl_comb/mark-frm.html"

    if pk:
        o = Mark.objects.filter(id=pk).first()
        frm = MarkForm(instance=o)
    else:
        frm = MarkForm()
    
    context["form"] = frm
    context["obj"] = o
    return render(request,template_name,context)

# class ModeloList(LoginRequiredMixin,PermissionRequiredMixin, ListView):
class ModeloList(SinAutorizacion, ListView):
    template_name="ctrl_comb/modelo.html"
    model=Modelo
    context_object_name = "obj"
    ordering= ["mark","descript"]
    login_url = "usuarios:login"
    permission_required = "ctrl_comb.view_modelo"
    # raise_exception = False
    # redirect_field_name = "redirect_to"

    # def form_invalid(self,form):
    #     response = super().form_invalid(form)
    #     if self.request.is_ajax():
    #         return JsonResponse(form.errors,status=400)
    #     else:
    #         return response
    
    # def handle_no_permission(self):
    #     from django.http import HttpResponseRedirect
    #     from django.contrib.auth.models import AnonymousUser
    #     if not self.request.user == AnonymousUser():
    #         self.login_url = "pages:forbidden"
    #     return HttpResponseRedirect(reverse_lazy(self.login_url))

class ModeloNew(CreateView):
    model=Modelo
    template_name="ctrl_comb/modelo_form.html"
    context_object_name="obj"
    form_class=ModeloForm
    success_url=reverse_lazy("control:modelo_list")

class ModeloEdit(UpdateView):
    model=Modelo
    template_name="ctrl_comb/modelo_form.html"
    context_object_name="obj"
    form_class=ModeloForm
    success_url=reverse_lazy("control:modelo_list")

class ModeloDelete(DeleteView):
    model=Modelo
    template_name="bases/delete.html"
    context_object_name="obj"
    success_url=reverse_lazy("control:modelo_list")


class ModeloEditModal(SinAutorizacion,MixinSaveUser,UpdateView):
    model=Modelo
    template_name="ctrl_comb/modelo_modal.html"
    context_object_name="obj"
    form_class=ModeloForm
    success_url=reverse_lazy("control:modelo_list")

    login_url = "usuarios:login"
    permission_required = "ctrl_comb.change_modelo"

    # def form_valid(self,form):
    #     print(f"************{form.instance.id} --- {self.request.user.id} *******************")

    #     if form.instance.id:
    #         form.instance.um = self.request.user
    #     else:
    #         form.instance.uc = self.request.user
        
    #     return super().form_valid(form)
    

class ModeloNewModal(SinAutorizacion,MixinSaveUser,CreateView):
    model=Modelo
    template_name="ctrl_comb/modelo_modal.html"
    context_object_name="obj"
    form_class=ModeloForm
    success_url=reverse_lazy("control:modelo_list")
    login_url = "usuarios:login"
    permission_required = "ctrl_comb.add_modelo"

    # def form_valid(self,form):
    #     print(f"************{form.instance.id} --- {self.request.user.id} *******************")

    #     if form.instance.id:
    #         form.instance.um = self.request.user
    #     else:
    #         form.instance.uc = self.request.user
        
    #     return super().form_valid(form)



@login_required(login_url="usuarios:login")
@permission_required("ctrl_comb.view_modelo")
def modelo_dt(request):
    context = {}
    datos = request.GET

    draw = int(datos.get("draw"))
    start = int(datos.get("start"))
    length = int(datos.get("length"))
    search = datos.get("search[value]")

    registros = Modelo.objects.all()

    if search:
        registros = registros.filter(
            Q(mark__descript__icontains=search) |
            Q(descript__icontains=search)
        )
    
    recordsTotal = registros.count()
    # recordsFiltered = recordsTotal

    context["draw"] = draw
    context["recordsTotal"] = recordsTotal
    context["recordsFiltered"] = recordsTotal

    reg = registros[start:start + length]
    paginator = Paginator(reg,length)

    try:
        obj = paginator.page(draw).object_list
    except PageNotAnInteger:
        obj = paginator.page(draw).object_list
    except EmptyPage:
        obj = paginator.page(paginator.num_pages).object_list
    
    # datos = []
    # for o in obj:
    #     datos.append({"id":o.id,"mark":o.mark__descript,"descript":o.descript})
    datos = [
        {
            "id" : o.id, "mark":o.mark.descript,"descript":o.descript
        } for o in obj
    ]

    context["datos"] = datos
    return JsonResponse(context,safe=False)


class VehiculoList(SinAutorizacion,TemplateView):
    template_name="ctrl_comb/vehiculo.html"
    login_url="core:home"
    permission_required = "ctrl_comb.view_vehiculo"


@login_required(login_url="usuarios:login")
@permission_required("ctrl_comb.view_vehiculo")
def vehiculo_dt(request):
    context = {}
    datos = request.GET

    draw = int(datos.get("draw"))
    start = int(datos.get("start"))
    length = int(datos.get("length"))
    search = datos.get("search[value]")

    if request.user.is_superuser:
        registros = Vehiculo.objects.all()
    else:
        registros = Vehiculo.objects.filter(uc = request.user)

    if search:
        registros = registros.filter(
            Q(modelo__mark__descript__icontains=search) |
            Q(modelo_descript__icontains=search) |
            Q(register__icontains=search) |
            Q(year__icontains=search)
        )
    
    recordsTotal = registros.count()
    # recordsFiltered = recordsTotal

    context["draw"] = draw
    context["recordsTotal"] = recordsTotal
    context["recordsFiltered"] = recordsTotal

    reg = registros[start:start + length]
    paginator = Paginator(reg,length)

    try:
        obj = paginator.page(draw).object_list
    except PageNotAnInteger:
        obj = paginator.page(draw).object_list
    except EmptyPage:
        obj = paginator.page(paginator.num_pages).object_list
    
    datos = [
        {
            "id" : o.id, "mark":o.modelo.mark.descript,"modelo":o.modelo.descript,
            "register":o.register,"year":o.year
        } for o in obj
    ]

    context["datos"] = datos
    return JsonResponse(context,safe=False)



class VehiculoNewModal(SinAutorizacion,MixinSaveUser,CreateView):
    model=Vehiculo
    template_name="ctrl_comb/vehiculo_modal.html"
    context_object_name="obj"
    form_class=VehiculoForm
    success_url=reverse_lazy("control:vehiculo_list")
    login_url = "usuarios:login"
    permission_required = "ctrl_comb.add_vehiculo"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["marcas"] = Mark.objects.all()
        context["modelos"] = Modelo.objects.all()
        return context

class VehiculoEditModal(SinAutorizacion,MixinSaveUser,UpdateView):
    model=Vehiculo
    template_name="ctrl_comb/vehiculo_modal.html"
    context_object_name="obj"
    form_class=VehiculoForm
    success_url=reverse_lazy("control:vehiculo_list")
    login_url = "usuarios:login"
    permission_required = "ctrl_comb.change_vehiculo"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["marcas"] = Mark.objects.all()
        context["modelos"] = Modelo.objects.all()
        return context


class VehiculoDelete(DeleteView):
    model=Vehiculo
    template_name="bases/delete.html"
    context_object_name="obj"
    success_url=reverse_lazy("control:vehiculo_list")

ctrl_comb/templates/ctrl_comb/mark-frm.html
<form hx-post = "{% url 'control:mark_save' %}" hx-target="#list"
 class="d-flex align-item-center" method="POST">
    <fieldset>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="id" class="form-label">Id</label>
                    <input type="text" class="form-control" id="id" aria-describedby="idhelp"
                    name="id" placeholder="id" readonly value="{{obj.id}}">
                    <small id="idthelp" class="form-text text-muted">Id</small>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="descript" class="form-label">Descripción</label>
                    <input type="text" class="form-control" id="descript" aria-describedby="idhelp"
                    name="descript" placeholder="Descripción" value="{{obj.descript}}">
                    <small id="descripthelp" class="form-text text-muted">Descripción</small>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-success btn-sm">Guardar</button>
            </div>
            <div class="col-md-6">
                <button type="button" class="btn btn-info btn-sm"
                hx-get="{% url 'control:mark_list' %}" hx-target="#body"
                >Limpiar</button>
            </div>
        </div>
    </fieldset>
</form>

ctrl_comb/templates/ctrl_comb/mark-list.html
{% if obj %}
<table class="table table-striped table-hover">
    <thead>
        <th>ID</th>
        <th>Descripción</th>
        <th>Acciones</th>
    </thead>
    <tbody>
        {% for o in obj %}
        <tr>
            <td>{{o.id}}</td>
            <td>{{o.descript}}</td>
            <td>
                <i class="bi bi-trash3"
                style="cursor: pointer;"
                hx-delete="{% url 'control:mark_delete' o.id %}"
                hx-target="#list"
                hx-confirm="¿Seguro que desea eliminar el registro?"
                ></i>
                <i class="bi bi-pencil-square"
                style="cursor: pointer;"
                hx-get="{% url 'control:mark_edit' o.id %}"
                hx-target="#frm"
                ></i>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No hay registros</p>
{% endif %}

<input type="text" class="form-control" id="id" aria-describedby="idhelp"
                    name="id" placeholder="id" readonly value="{{reg.id}}"
                    hx-swap-oob="true">
                    

ctrl_comb/templates/ctrl_comb/mark.html
{% extends "base.html" %}
{% load static %}

{% block contenido %}

{% include "fragments/titulo.html" with titulo="Marca Vehículo"  %}

    {% include "fragments/card_start.html" with header="" %}
    <div class="row">
        <div class="col-md-6">
            <div id="frm">
                {% include 'ctrl_comb/mark-frm.html' %}
            </div>
        </div>
        <div class="col-md-6">
            <div id="list">
                {% include 'ctrl_comb/mark-list.html' %}
            </div>
        </div>
    </div>
      {% include "fragments/card_finish.html" %}
{% endblock %}

{% block js %}
<!-- <script>
$(function(){
    $("#tbl").DataTable({
        language:{
            url: "{% static 'plugins/datatable/es.json' %}"
        }
    })
})
</script> -->
{% endblock %}

ctrl_comb/templates/ctrl_comb/modelo.html
{% extends "base.html" %}

{% block contenido %}

{% include "fragments/titulo.html" with titulo="Modelos Vehículo"  %}

    {% include "fragments/card_start.html" with header="Listado de Modelos de Vehículos" %}
    <a href="{% url 'control:modelo_new' %}" class="btn btn-sm btn-warning"><i class="bi bi-plus-circle"></i>Nuevo</a>
    <button type="button" class="btn btn-success btn-sm" onclick="abrir_modal('{% url 'control:modelo_new_modal' %}')">
        <i class="bi bi-pencil-square"></i>
    </button>
    <table id="tbl" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <!-- {#% for o in obj %#}
            <tr>
                <td>
                    <a href="{#% url 'control:modelo_edit' o.id %#}" class="btn btn-info btn-sm">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    <a href="{#% url 'control:modelo_delete' o.id %#}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                    <button type="button" class="btn btn-danger btn-sm" onclick="borrar({{o.id}},'{{o.descript}}')">
                        <i class="bi bi-trash3"></i>
                    </button>
                    <button type="button" class="btn btn-success btn-sm" onclick="abrir_modal('{#% url 'control:modelo_edit_modal' o.id %#}')">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                </td>
                <td>{{ o.mark }}</td>
                <td>{{ o.descript }}</td>
            </tr>
            {#% endfor %#} -->
        </tbody>
    </table>
    {% include "fragments/card_finish.html" %}
{% endblock %}


{% block js %}
{% endblock %}

{% block dtName %}#tbl{% endblock %}
{% block dtColumns %}
{ data:"mark"},{ data:"descript"}
{% endblock %}
{% block dtUrl %}{% url 'control:modelo_dt' %}{% endblock %}
{% block dtUrlEdit %}/control/models/modal{% endblock %}
{% block dtUrlDelete %}{% url 'control:modelo_list' %}delete/{% endblock %}
{% block dtDescDelete %}mark,descript,algo{% endblock %}

ctrl_comb/templates/ctrl_comb/modelo_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block contenido %}

{% include "fragments/titulo.html" with titulo="Modelos Vehículo"  %}

    {% include "fragments/card_start.html" with header="Agregar/Editar Modelos de Vehículos" %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-stop-circle"></i> Guardar</button>
                <a href="{% url 'control:modelo_list' %}"><i class="bi bi-x-octagon-fill"></i> Cancelar</a>
            </div>
        </div>
    </form>
    {% include "fragments/card_finish.html" %}
{% endblock %}


{% block js %}
{% endblock %}

ctrl_comb/templates/ctrl_comb/modelo_modal.html
{% load crispy_forms_tags %}

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <form action="{{ request.path }}" method="POST">
            {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
            </button>
        </div>
        <div class="modal-body">
            {{ form|crispy }}
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-stop-circle"></i> Guardar</button>
            <!-- <a href="{% url 'control:modelo_list' %}"><i class="bi bi-x-octagon-fill"></i> Cancelar</a> -->
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        </div>
    </form>
    </div>
</div>

ctrl_comb/templates/ctrl_comb/vehiculo.html
{% extends "base.html" %}

{% block contenido %}

{% include "fragments/titulo.html" with titulo="Vehículo"  %}

    {% include "fragments/card_start.html" with header="Listado de Vehículos" %}
    <button type="button" class="btn btn-success btn-sm" onclick="abrir_modal('{% url 'control:vehiculo_new' %}')">
        <i class="bi bi-pencil-square"></i>
    </button>
    <table id="tbl" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Registro</th>
                <th>Año</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    {% include "fragments/card_finish.html" %}
{% endblock %}


{% block js %}
{% endblock %}

{% block dtName %}#tbl{% endblock %}
{% block dtColumns %}
{ data:"mark"},{ data:"modelo"},{ data:"register"},{ data:"year"}
{% endblock %}
{% block dtUrl %}{% url 'control:vehiculo_dt' %}{% endblock %}
{% block dtUrlEdit %}/control/vehicles/modal{% endblock %}
{% block dtUrlDelete %}{% url 'control:vehiculo_list' %}delete/{% endblock %}
{% block dtDescDelete %}mark,modelo,register,year{% endblock %}

ctrl_comb/templates/ctrl_comb/vehiculo_modal.html
{% load crispy_forms_tags %}

<div class="modal-dialog modal-fullscreen" role="document">
    <div class="modal-content">
        <form action="{{ request.path }}" method="POST">
            {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title">{% if obj %}Editar {% else %}Nuevo {% endif %} Vehículo</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
            </button>
        </div>
        <div class="modal-body">
            {#{ form|crispy }#}
            <div class="row">
                <div class="col-6">
                    <select name="mark" id="id_mark" class="select form-select">
                        <option value="">Seleccione Marca</option>
                        {% for o in marcas%}
                        <option value="{{o.id}}">{{o.descript}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-6">
                    <select name="modelo" id="id_modelo" class="select form-select">
                        <option value="">Seleccione Modelo</option>
                        {% for o in modelos%}
                        <option value="{{o.id}}" data-chained="{{o.mark.id}}">{{o.descript}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-6">{{form.register|as_crispy_field}}</div>
                <div class="col-6">{{form.year|as_crispy_field}}</div>
            </div>
            <div class="row">
                <div class="col-6">{{form.tipo|as_crispy_field}}</div>
                <div class="col-6">{{form.unidad_medida|as_crispy_field}}</div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-stop-circle"></i> Guardar</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-octagon-fill"></i>Cancelar</button>
        </div>
    </form>
    </div>
</div>


<script>
    $(function(){

        {% if obj %}
        $("#id_mark").val("{{obj.modelo.mark.id}}").trigger('change')
        $("#id_modelo").val("{{obj.modelo.id}}").trigger('change')


        $("#tipo").val("{{obj.tipo}}")
        $("#unidad_medida").val("{{obj.unidad_medida}}")
        {% endif %}

        $(".form-select").select2(
            {
                theme: 'bootstrap-5'
            }
        );
        $("#id_modelo").chained("#id_mark");
    })
</script>